### PR TITLE
V8 5.4.9

### PR DESCRIPTION
**Pull request by iefserge**

### CODE REVIEW

**Comment by piranna** [comment]
Why instead of bundle a copy of v8 in the source tree it's not downloaded
from upstream on an initial step as NodeOS generator does? Is it being
applied some patch to the v8 code? If so, why not apply it instead on
download step, too?

**Comment by iefserge** [comment]
@piranna Few reasons, of course there are possibilities for improvement:
- yeah, v8 is patched a bit, things that deal with OS APIs. This can be improved by directly supporting functions like gettimeofday etc.
- v8 build system creates some generated files, converts js files into c++ byte arrays. This would require running v8 build system once.
- Snapshot needs to be generated for faster startup, this requires running QEMU once.

**Comment by piranna** [comment]
Definitely that complicate things and would make build process slower... :-/

**Comment by piranna** [comment]
Just a suggestion for the future: since v8 needs to be included because
there are some parts that need to be autogenerated, why not host this
autogenerated v8 on another repo and just download it? This would make more
clear runtime.js repo, and v8 one could be auto-updated itself... This is
what I'm currently doing with NodeOS, to make a mechanism to keep
auto-updated all the external dependencies...

**Pull request merged**
