### PR TITLE
JS test runner

### PR DESCRIPTION
**Pull request by iefserge**
@kesla this uses postinstall script to link `../js`

### CODE REVIEW

**Comment by iefserge** [comment]
or maybe it would be simpler to just change `require('runtimejs')` to `require('../')` in tests

**Comment by kesla** [comment]
@iefserge yeah rewriting them might be simpler - I don't really see the value of a separate package.json?

**Comment by kesla** [comment]
@iefserge any progress on this? Are we rewriting the tests to use relative paths?

**Comment by iefserge** [comment]
@kesla yep, its done. closing this

**Pull request closed without merging**
