### PR TITLE
Add missing license headers, add authors

### PR DESCRIPTION
**Pull request by iefserge**
R = @kesla @ArielAbreu

### CODE REVIEW

**Comment by ArielAbreu** [comment]
:+1:

**Comment by ArielAbreu** [comment]
:-1: Just kidding! :+1:

**Comment by kesla** [comment]
Yeah!

**Comment by ArielAbreu** [comment]
@iefserge Uh, saw this just merged, guess this is late, but... I changed my email to "ariel.abreu@outlook.com".

**Comment by iefserge** [comment]
@ArielAbreu fixed

**Comment by ArielAbreu** [comment]
Thanks.

**Pull request merged**
