### PR TITLE
[wip] make keyboard compatible with browser

### PR DESCRIPTION
**Pull request by kesla**
- [x] keyboard.on{Keydown, Keyup} -> keyboard.on{keydown, keyup}
- [ ] change event to be the same as https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

### CODE REVIEW

**Comment by iefserge** [comment]
Awesome, great to have a compatible api!

**Comment by piranna** [comment]
> Awesome, great to have a compatible api!

:+1: Hope there's something similar in Node.js area :-)

**Comment by kesla** [comment]
@iefserge  I started thinking about this a little more - perhaps we're doing it wrong here and a little bit more complicated than necessary - wouldn't emitting the char be enough? That's how node does it so could make is simple to create compatibility with `process.stdin` at some point :)

**Comment by iefserge** [comment]
`stdin` could be a layer on top of raw keyboard input events.

**Comment by piranna** [comment]
> `stdin` could be a layer on top of raw keyboard input events.

+1

**Pull request closed without merging**
