### PR TITLE
Remove builtin commands

### PR DESCRIPTION
**Pull request by ArielAbreu**
Remove builtins from runtimejs, since I added more commands in an optional module called `runtime-shell`. I've already opened this PR before, but, I accidentally deleted the branch, so... I recreated it and opened it again.

### CODE REVIEW

**Comment by iefserge** [comment]
@ArielAbreu I think it's a good idea to move commands out of core to runtime-shell, except maybe reboot/poweroff because they're very system dependent.

**Comment by iefserge** [comment]
Like `echo` and `clear` are part of shell for sure.

**Comment by ArielAbreu** [comment]
I'll redo the PR because it I accidentally deleted the repository.

**Comment by piranna** [comment]
> except maybe reboot/poweroff because they're very system dependent

I would move them too, and only allow them as an API.

**Comment by ArielAbreu** [comment]
I agree with @piranna, anything that is added for convenience <i>can<i> (not must) be moved out into a module.

**Comment by iefserge** [comment]
@piranna hm, I use them very frequently when debugging runtime in KVM in curses mode, however I don't need full shell for that

**Comment by iefserge** [comment]
(I can remotely ssh to linux machine and run runtime in KVM without graphical interface)

**Comment by ArielAbreu** [comment]
I've been working on a telnet server for runtime which listens on port 9000 (the forwarded port) which can be used for more direct remote control. That aside,  if `shutdown` and `poweroff` are going to be the only commands, maybe they could be moved into `index.js` with command `1`.

**Comment by iefserge** [comment]
@ArielAbreu sounds good, let's do this

**Comment by ArielAbreu** [comment]
Opened #69.

**Pull request closed without merging**
