### PR TITLE
Remove builtins

### PR DESCRIPTION
**Pull request by ArielAbreu**
I'd like to remove the shell functions (ironic, since I added them) in favor of a module containing them (plus `ping`). This was discussed after the merge for #58 and I believe it's better to add them as a module  (as suggested). I've gone ahead and created a <a href="https://www.npmjs.com/package/runtime-shell">module on NPM called "runtime-shell"</a> containing the commands.

### CODE REVIEW

**Comment by ArielAbreu** [comment]
Wait, fixing little bug...

**Comment by iefserge** [comment]
@ArielAbreu I think shell module shouldn't depend on runtime directly and it should be passed as an argument like `require('runtime-shell')(runtime)`.
Note: `runtime.shell.setCommand` is probably going to change.

**Comment by iefserge** [comment]
I think the biggest issue with current interface is that it's not easy to redirect input/output from tty to somewhere else.

**Comment by ArielAbreu** [comment]
I'm also working on launching she'll commands from an application.

**Comment by ArielAbreu** [comment]
And about depending, that is better and it's what I use for multiple files.

**Comment by iefserge** [comment]
The problem with dependency on runtime is that it forces everyone to use the version of runtime that is bundled with shell and not the one user would like to require.

**Comment by iefserge** [comment]
btw runtime registers itself as a global `runtime` object, that's another way to use it

**Comment by ArielAbreu** [comment]
No, I mean (if you see the source, you'll see it too) that passing runtime in is better that's what I do to require the shell commands. Plus, I just fixed that, just need to publish it on npm.

**Comment by iefserge** [comment]
I'd say let's figure out better interface for commands that supports input/output redirection and doesn't always push output into tty.

**Comment by iefserge** [comment]
I'm not completely sure if global runtime object is good idea though, we might want to remove that.

**Comment by ArielAbreu** [comment]
Yes, a better interface is needed. Also, a way of getting Input **easily** from inside an app. Right now, it can be done, but you have set a listener for key down and manage keys and newlines, etc.

**Comment by ArielAbreu** [comment]
The global is sort of iffy, because it can be useful, but if the user wants to have runtimejs under a different name it isn't, ideal. (I've got message lag)

**Comment by iefserge** [comment]
Opened an issue in runtime-shell https://github.com/ArielAbreu/runtime-shell/issues/1

**Comment by piranna** [comment]
> I'm not completely sure if global runtime object is good idea though, we might want to remove that.

Me too, also but being a dependency it would allow to define with what version (of the API) of runtime it's compatible

**Comment by ArielAbreu** [comment]
@piranna True, but runtime-shell should be able to work any (newer) version of runtimejs. Seems logical to have whatever version the user wants.

**Comment by iefserge** [comment]
@piranna we might want to use a peerDependency

**Comment by ArielAbreu** [comment]
I just pushed an update to npm that accepts runtime as an argument.

**Comment by ArielAbreu** [comment]
I published a new update to it that accepts it as a peerDependency, and makes passing runtime to the module optional.

**Comment by iefserge** [comment]
@ArielAbreu in my opinion, if there is a peer dependency, optional argument would make it very confusing. I'd say let's just use the peerDependency and remove the argument.

**Comment by ArielAbreu** [comment]
Ok, i'll push the update

**Comment by iefserge** [comment]
@piranna @kesla @ArielAbreu I'm curious what do you guys think the best way to manage plugin dependencies?

**Comment by ArielAbreu** [comment]
I didn't know about peerDependencies until today, I think either peerDependencies or regular dependencies, that way it can request a specific version.

**Comment by piranna** [comment]
> @piranna True, but runtime-shell should be able to work any (newer) version of runtimejs. Seems logical to have whatever version the user wants.

Yes, but that's why semver was invented... ;-) Shell could have runtime ^0.1.0 as dependency and it will work with newer versions...

**Comment by ArielAbreu** [comment]
@piranna I added a ping command to shell (needs tcp), and TCP was introduced in what version? 0.1.3-0.1.4, right? Yes, it could have it as a dependency, but versions ^0.1.4 would work with it. BTW, there is a discussion issue (ArielAbreu/runtime-shell#1) in runtime-shell.

**Comment by iefserge** [comment]
while versions are <1.0 each update could be breaking, I guess peer dependency "0.x" would be ok

**Comment by ArielAbreu** [comment]
Closing pull request for now, it conflicts with a more important PR (#60).

**Comment by kesla** [comment]
@ArielAbreu how could this PR conflict with another PR?

**Comment by ArielAbreu** [comment]
I'm reopening it because it turns out it wasn't conflicting.

**Comment by ArielAbreu** [comment]
Whoops, deleted this branch by accident. That's OK! I just deleted the files. I'll do it again.

**Pull request closed without merging**
